### ISSUE TITLE
Ensure strict mode in every single JS file

### ISSUE THREAD

**Issue by allaudet** [talyssonoc/node-api-boilerplate#23]
I've seen that some files have it and others don't, and could be worth adding in all of them.
What do you think?

**Comment by talyssonoc** [comment]
The only ones that have it are because they were auto-generated by Sequelize CLI and are not necessary because of the min Node version of the project and by the fact they're just for the example app and are deleted after the cleanup, so I think it's not worth to add it to all the files.
