### ISSUE TITLE
how would a Mapper support relationships?

### ISSUE THREAD

**Issue by LiranBri** [talyssonoc/node-api-boilerplate#39]
Hi,
When you have simple data-values objects such as your User, a Mapper is pretty simple as it just maps the properties between DB model and domain.

but how would you deal with relationships?
for example, if a User can potentially have a "ReferrerUser".

now the mapper should support both user with and without a referrer user.
the problem is "lazy loading". sometimes you want just the Id of the referrer, and sometimes the actual user object, depending on the use-case.

examples for different scenarios:
1. create a user without referrer
2. create a user + create its user referrer at the same time
3. create a user with user id of the user referer (it already exists in the system)
4. fetch user with just its referer id if exists
5. fetch user + eagerly fetch the referrer user as a nested object

also, what if I now also want the user to have a collection of all the users he referred? I would add "referredUsers" array to the domain
the problem is that sometimes I would want to fetch just the user, and sometimes I would want to fetch the user + his referred users (eager loading). and so on ..

moreover, in this example, the relationship is to the same type. what if the relationship is to another type? for example, if User has a relationship to "Country". now I would also need to delegate a call to CountryMapper inside UserMapper?

lastly, when there is no 1-to-1 connection between the domain and the table persisting it, mapper might impose more difficulties to "glue" things together

hope my concerns are clear

**Comment by CharlyJazz** [comment]
insane

**Comment by CharlyJazz** [comment]
why you close it without a explanation, make the repo privately if you dont want help the people that trust in you

**Comment by talyssonoc** [comment]
This repository is a boilerplate, not a source of documentation about good practices. There is a lot of content in the wiki of the project https://github.com/talyssonoc/node-api-boilerplate/wiki/Patterns-recommendations-and-operations. A lot of questions can only be answered by people that are in the project itself, not in a generic way.

Also, this is open source and I do it all for _free_, so I do with it whatever I want, don't you try to say me whether I should leave it public or private.

**Comment by LiranBri** [comment]
@CharlyJazz don't be rude. Even though I was also disappointed for the fact that the owner closed the ticket without replying anything, it is his choice and only his whether to give support or reply to his users

**Comment by CharlyJazz** [comment]
It is rude and selfish behavior. We all have to be responsible for what we climb to Github.
