### ISSUE TITLE
How to deal with association many to many ? 

### ISSUE THREAD

**Issue by postel5u** [talyssonoc/node-api-boilerplate#41]
Hi,
With my mate, we are junior developper and we try to refactor our system with your boilerplate ! I have just a problem during my learning process, i had try to do a new Model Team (no problem for this) and now i try to do a n-n relation with pivot table TeamsUsers. I haven't find any example of this and i don't see how to make it properly. 
Can i get a simple example or some link with info about this ?
Hope my sentences are clear !

**Comment by saelfaer** [comment]
1) firstly,  not related to this boilerplate,
what database are you using in your project, and are you also adopting sequelize from this boilerplate or are you using something else?

as that of course greatly impacts the way you will set-up your n-n relations.

2) Besides the setup of the pivot table and relation in your model, you need to think about your routing as well. for example,  are you going to add subroutes? or specific other routes for your relations
for example:

/api/users/:userId/teams  (GET: to list teams from a user,  POST to create a new team-user releationship...)
or will you be adding specific routes like
/api/teamsusers  [the whole crud on the relation itself]
