### ISSUE TITLE
Promises vs EventEmitter

### ISSUE THREAD

**Issue by Lughino** [talyssonoc/node-api-boilerplate#44]
Hi @talyssonoc,
really great boilerplate!

I've got a question, where I'm struggling to get a good justification to use EventEmitter rather than Promises in response to the `execute` method in every `Operation`...

The only advantage that I see so far with the `EventEmitter` approach is the ability to `subscribe` the operation in different part of the application...
It should not be an easiest approach to return a promise from the `execute` method where the `success` of the promise would return the result and the `failure` would return the error?
This would also reduce the memory leak produced by the `EventEmitter`.

**Comment by talyssonoc** [comment]
Hello @Lughino, thanks for your question!

The reason for the use of event emitters is so we don't need to make assertions over the error returned from the failure of the promise at the input layer to discover the reason for the failure. Using event allows you to emit a different event for each possible outcome of the use case. You can read more about that in my post about [NodeJS and Good Practices](https://blog.codeminer42.com/nodejs-and-good-practices-354e7d763626), specifically in the "NodeJS and the application layer" section.
