### ISSUE TITLE
AwilixTypeError  when trying to resolve a registered dependency 

### ISSUE THREAD

**Issue by pointer** [talyssonoc/node-api-boilerplate#47]
**type** :  "InternalServerError"
**message** : "build: expected targetOrResolver to be a function or class, but got userSerializer."
**stack** : "AwilixTypeError: build: expected targetOrResolver to be a function or class, but got userSerializer.\n    at Function.assert (c:\\_dev\\sgdtserver\\node_modules\\awilix\\lib\\errors.js:83:19)\n    at Object.build (c:\\_dev\\sgdtserver\\node_modules\\awilix\\lib\\container.js:337:30)\n    at middlewareFactoryHandler (c:\\_dev\\sgdtserver\\node_modules\\awilix-express\\lib\\invokers.js:106:34)\n    at Layer.handle [as handle_request] (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (c:\\_dev\\sgdtserver\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at scopePerRequestMiddleware (c:\\_dev\\sgdtserver\\node_modules\\awilix-express\\lib\\scope-per-request.js:13:16)"

**Comment by talyssonoc** [comment]
Hello, @pointer, this must be because of the way you're registering the userSerializer or your Awilix version. This question would fit better in the [awilix repo](https://github.com/jeffijoe/awilix).
