### ISSUE TITLE
Didn't see service, repository, usecases

### ISSUE THREAD

**Issue by mrdulin** [talyssonoc/node-api-boilerplate#48]
I think this boilerplate should be improved.

**Comment by talyssonoc** [comment]
There is a use case here: https://github.com/talyssonoc/node-api-boilerplate/blob/master/src/app/user/CreateUser.js
And a repository here: https://github.com/talyssonoc/node-api-boilerplate/blob/master/src/infra/user/SequelizeUsersRepository.js

The example application is too simple to justify the use of a service.

The idea is to provide a boilerplate of a application that makes it easy to use a good architecture, not to serve an example for every Clean Architecture or DDD tactical patterns.
