### ISSUE TITLE
Upgrade Sequelize to v4

### ISSUE THREAD

**Issue by talyssonoc** [talyssonoc/node-api-boilerplate#5]
Right now we use Sequelize v3, the migration to the new version is not hard to achieve: http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

--

Update: I'll hold it until [Sequelize CLI](https://github.com/sequelize/cli) updates to generate classes on `model:create` command, or at least until it [stop generating the models using `classMethod`](https://github.com/sequelize/cli/pull/470).

**Comment by sethigoldy** [comment]
Can you upgrade to latest sequelize v4
