### ISSUE TITLE
An folder structure example needed 

### ISSUE THREAD

**Issue by moda20** [talyssonoc/node-api-boilerplate#50]
Hey !

I want a little help in understanding your folder and dependency injection structure : 

If I am trying to implement an external Emailing WebAPI (SendGrid), how do I organize the files along your file structure ?

sendGrid basically has a library and I need to implement a wrapper around it. How do I do that.
 my solution so far is to : 

- create a database model (necessary)
- create a sendGridFolder under interfaces where I add the sendGridWrapper 
- create an Email Folder under infra then under it create SendGrid folder and within add a new Repository sendGridRepository that must have the sendgridWrapper injected to it via the constructor as well as the Database model.
- create a domain model named Email
- create an operation folder under app called Email and add email operations under it ( sending, checking status, .... ) this will use the domain model

Is this the correct way of using your approach ? 
if else can you please specify, in a flowchart type fashion, the steps that a basic db query coming from and API call to this system would take  ? ans maybe the files that it goes through ? something like this file will call this file and the use the dependency injected right here, .....

Thanks, you work is very good but I found it hard to understand with ease. so if you can spare some time to help me, this would be very nice.

**Comment by talyssonoc** [comment]
Hello, @moda20,

I wouldn't inject anything from the interfaces layer into the infra layer. If the wrapper is a way to talk to the SendGrid API, I would put it inside `infra` as well and call it `sendGridService`. Also, I wouldn't send emails from inside a repository, so I'd rather inject both the repository and the service into the operations and call them separately from there.

**Comment by moda20** [comment]
Yes, I would do add the wrapper in the infra layer too. 
But since the repository is supposed to house methods related to sending an email wouldn't it be better to inject the wrapper into the repository and then inject the repository in the operation ? 

or maybe even create a repository for the wrapper and a repository for the db or anything else, basically separating the repositories of different purposes.

**Comment by talyssonoc** [comment]
@moda20 repositories aren't supposed to send emails, these are services' responsibilities. Repositories aren't the only citizens on the infra layer, you can create a service that makes it explicit that an email will be sent instead of abstract it in collectoin-like named methods in repositories.

**Comment by talyssonoc** [comment]
Do you have something to add to the discussion, @dev5etech?
