### ISSUE TITLE
Trying to install dependencies using npm throws error

### ISSUE THREAD

**Issue by HenonoaH** [talyssonoc/node-api-boilerplate#53]
I'm trying to install dependencies using the node package manager (npm) but it throws an error in the middle of installation and stops further installation. I went through this [quick start](https://github.com/talyssonoc/node-api-boilerplate#quick-start) it says to install dependencies using yarn package manager but I thought of installing it via npm!

This is the snap of the error I got,
![image](https://user-images.githubusercontent.com/32451863/67551042-90ff1e80-f725-11e9-9372-ae08910fbeaf.png)

```
Node version is 10.16.3
NPM version is 6.9.0
OS Ubuntu 18.04.3 LTS
```

It could be great if we have both `npm` and `yarn` package manager support

**Comment by talyssonoc** [comment]
Sorry but there is no advantage in supporting both dependency managers.
