### ISSUE TITLE
Different input validations for different actions

### ISSUE THREAD

**Issue by noorzaie** [talyssonoc/node-api-boilerplate#63]
Hi. Usually we need different schema validations for different actions on same entity. For example, we don't want to update some user's fields but we need them when creating new user. But we have just one schema for user in domain layer. Is it legal to create multiple schemas for create, update and other operations for one entity in domain layer?

**Comment by talyssonoc** [comment]
Sure! Actually, it's interesting to use different validators separated from the domain entity for each use case. Like having a `CreateUserInput` and a `UpdateUserInput` classes that validates the input specifically for each of these use cases.
