### ISSUE TITLE
use Heroku database in development

### ISSUE THREAD

**Issue by lasharela** [talyssonoc/node-api-boilerplate#64]
I'm trying to initiate a project with Heroku database in development mode.

I updated config/database.js:

```
  development: {
    username: 'XXXX',
    password: 'XXXXX',
    database: 'XXXXX',
    host: 'XXXXX.compute-1.amazonaws.com',
    dialect: 'postgres'
  },
```

Loaded configuration file "config/database.js".
Using environment "development".

ERROR: connect ECONNREFUSED 

What I'm doing wrong?

**Comment by charleston10** [comment]
You need start application with command "npm rum dev" for load "database.developement"

**Comment by talyssonoc** [comment]
Any message in the Heroku logs?

**Comment by wmigas** [comment]
heroku requires encryption for connections to database 
sslMode=require

**Comment by mhrsntrk** [comment]
Heroku needs SSL for outside connections. So you can read more in this article https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js
