### ISSUE TITLE
Can we use mongoDB?

### ISSUE THREAD

**Issue by ajayexpert** [talyssonoc/node-api-boilerplate#66]
Hi 

i wanted to use mongoDB for database so can we do that too?

**Comment by talyssonoc** [comment]
Yep! As long as you encapsulate the technology used behind the repositories, what you use to store your data is independent should not after your app.

**Comment by ajayexpert** [comment]
Is there any reference to do that? kind a noob in this technology.

**Comment by talyssonoc** [comment]
You can search more about the repository pattern, it intends to make the rest of your application independent from the database technology you're using.
