### ISSUE TITLE
How to use relationship using structure ?

### ISSUE THREAD

**Issue by fatkhanfauzi** [talyssonoc/node-api-boilerplate#8]
let say i have User and Role models
User has_one Role

how to return and assign the relation using structure js ?

how to map that in the Mapper ?

any idea ?

**Comment by talyssonoc** [comment]
Hey @fatkhanfauzi, I'm not sure if I understand your question. When declaring field types you can use other structure entities as the type of an attribute. To map it in the mapper you can have a mapper for each of the entities (user and role) and call then inside each other if needed.
